"use client";

import { useEffect, useState } from "react";
import { ApiError } from "@/lib/api/client";
import { confirmExtraction, extractInformation, ExtractedField, ExtractionDecision, ExtractionRecord, getLatestExtraction } from "@/lib/opportunities";

const labels: Record<string, string> = { company_name: "Company name", industry: "Industry", company_description: "Company description", location: "Location", website: "Website", funding_amount: "Funding amount", funding_currency: "Funding currency", funding_stage: "Funding stage", funding_date: "Funding date", investors: "Investors", product_name: "Product name", product_description: "Product description", product_launched: "Product launched", product_launch_date: "Product launch date", customer_count: "Customer count", user_count: "User count", revenue: "Revenue", revenue_growth: "Revenue growth", other_growth_metrics: "Other growth metrics", headquarters_location: "Headquarters", operating_markets: "Operating markets", expansion_markets: "Expansion markets", geographic_relevance: "Geographic relevance", founder_names: "Founder names", founder_roles: "Founder roles", founder_available_for_interview: "Founder available for interview", spokesperson_available: "Spokesperson available", target_audience: "Target audience", target_industries: "Target industries", key_claims: "Key claims", notable_announcements: "Notable announcements", important_dates: "Important dates", milestones: "Milestones", potential_news_hooks: "Potential news hooks" };
function display(value: ExtractedField["value"]) { return Array.isArray(value) ? value.join(", ") : value === true ? "Yes" : value === false ? "No" : value ?? "Not found"; }
function parse(input: string, original: ExtractedField["value"]): ExtractedField["value"] { if (Array.isArray(original)) return input.split(",").map((item) => item.trim()).filter(Boolean); if (typeof original === "number") return Number(input); if (typeof original === "boolean") return /^(true|yes)$/i.test(input); return input; }

export function InformationExtraction({ opportunityId }: { opportunityId: number }) {
  const [extraction, setExtraction] = useState<ExtractionRecord | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [review, setReview] = useState(false); const [raw, setRaw] = useState(false); const [error, setError] = useState<string | null>(null); const [decisions, setDecisions] = useState<Record<string, ExtractionDecision>>({});
  const showError = (reason: unknown) => setError(reason instanceof ApiError ? reason.message : "Unable to complete information extraction.");
  useEffect(() => { void getLatestExtraction(opportunityId).then((result) => { setExtraction(result); if (result?.confirmation) setDecisions(result.confirmation.decisions); }).catch(showError).finally(() => setLoading(false)); }, [opportunityId]);
  const prepare = (result: ExtractionRecord) => { const next: Record<string, ExtractionDecision> = {}; Object.entries(result.fields).forEach(([name, item]) => { next[name] = { action: item.extraction_status === "extracted" ? "accepted" : "rejected", value: item.value }; }); setDecisions(next); setReview(true); };
  async function extract() { try { setBusy(true); setError(null); const result = await extractInformation(opportunityId); setExtraction(result); prepare(result); } catch (reason) { showError(reason); } finally { setBusy(false); } }
  async function confirm() { if (!extraction) return; try { setBusy(true); setError(null); const result = await confirmExtraction(opportunityId, extraction.id, decisions); setExtraction(result.extraction); setReview(false); } catch (reason) { showError(reason); } finally { setBusy(false); } }
  if (loading) return <section className="extraction-panel"><p className="muted-copy">Loading AI analysis…</p></section>;
  const fields = extraction ? Object.entries(extraction.fields).filter(([, item]) => item.extraction_status === "extracted" || review) : [];
  return <section className="extraction-panel"><p className="eyebrow">AI information extraction</p><h2>Structured facts from the client briefing</h2>{error && <p className="form-error" role="alert">{error}</p>}{!extraction && <><p className="muted-copy">Analyze the briefing for factual company, funding, product, traction, people, and PR-relevant information. Nothing is applied until a consultant confirms it.</p><button className="primary-button" disabled={busy} onClick={() => void extract()} type="button">{busy ? "Analyzing client briefing…" : "Extract information"}</button></>}{extraction && !review && !extraction.confirmation && <><p className="muted-copy">Extraction completed. Review the findings before adding them to the opportunity.</p><button className="primary-button" onClick={() => prepare(extraction)} type="button">Review & confirm</button></>}{extraction?.confirmation && <p className="confirmation-note">Confirmed {new Date(extraction.confirmation.confirmed_at).toLocaleString()}. The original AI extraction is preserved for audit purposes.</p>}{fields.length > 0 && <div className="extraction-fields">{fields.map(([name, item]) => { const decision = decisions[name]; return <article className="extraction-field" key={name}><h3>{labels[name] ?? name}</h3>{review ? <><input aria-label={`${labels[name]} value`} disabled={decision?.action === "rejected"} onChange={(event) => setDecisions((current) => ({ ...current, [name]: { action: "edited", value: parse(event.target.value, item.value) } }))} value={display(decision?.value ?? item.value)} /><div className="field-actions">{(["accepted", "edited", "rejected"] as const).map((action) => <button className={decision?.action === action ? "selected" : ""} key={action} onClick={() => setDecisions((current) => ({ ...current, [name]: { action, value: action === "rejected" ? null : current[name]?.value ?? item.value } }))} type="button">{action === "accepted" ? "Accept" : action === "edited" ? "Edit" : "Reject"}</button>)}</div></> : <p className="extracted-value">{display(extraction?.confirmation?.decisions[name]?.value ?? item.value)}</p>}<p className="confidence">Confidence: {Math.round(item.confidence * 100)}%</p><p className="source-text">Source: “{item.source_text}”</p></article>; })}</div>}{review && <button className="primary-button" disabled={busy} onClick={() => void confirm()} type="button">{busy ? "Confirming…" : "Confirm extracted information"}</button>}{extraction && <button className="raw-toggle" onClick={() => setRaw(!raw)} type="button">{raw ? "Hide raw extraction" : "View raw extraction"}</button>}{raw && extraction && <pre className="raw-extraction">{JSON.stringify(extraction.fields, null, 2)}</pre>}</section>;
}
