"use client";
import { useEffect, useState } from "react";
import { ApiError } from "@/lib/api/client";
import { getLatestScore, getScoreHistory, OpportunityScore, scoreOpportunity } from "@/lib/opportunities";
const labels: Record<string, string> = { newsworthiness: "Newsworthiness", media_appeal: "Media Appeal", timeliness: "Timeliness", credibility: "Credibility", audience_interest: "Audience Interest" };
export function OpportunityScorePanel({ opportunityId }: { opportunityId: number }) {
  const [score, setScore] = useState<OpportunityScore | null>(null); const [history, setHistory] = useState<OpportunityScore[]>([]); const [loading, setLoading] = useState(true); const [analyzing, setAnalyzing] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = async () => { const [latest, scores] = await Promise.all([getLatestScore(opportunityId), getScoreHistory(opportunityId)]); setScore(latest); setHistory(scores); };
  useEffect(() => { void Promise.all([getLatestScore(opportunityId), getScoreHistory(opportunityId)]).then(([latest, scores]) => { setScore(latest); setHistory(scores); }).catch((reason) => setError(reason instanceof ApiError ? reason.message : "Unable to load the PR opportunity score.")).finally(() => setLoading(false)); }, [opportunityId]);
  async function analyze() { try { setAnalyzing(true); setError(null); const result = await scoreOpportunity(opportunityId); setScore(result); await load(); } catch (reason) { setError(reason instanceof ApiError ? reason.message : "Unable to analyze this opportunity."); } finally { setAnalyzing(false); } }
  if (loading) return <section className="score-panel"><p className="muted-copy">Loading PR opportunity analysis…</p></section>;
  return <section className="score-panel"><p className="eyebrow">PR opportunity analysis</p>{error && <p className="form-error" role="alert">{error}</p>}{!score ? <><h2>This opportunity has not been scored yet.</h2><p className="muted-copy">A deterministic quality score—not a guarantee of media coverage.</p><button className="primary-button" disabled={analyzing} onClick={() => void analyze()} type="button">{analyzing ? "Analyzing opportunity…" : "Analyze opportunity"}</button></> : <><div className="score-summary"><div><h2>PR Opportunity Score</h2><p className="score-number">{score.overall_score}<span> / 100</span></p><p className={`potential potential-${score.potential.toLowerCase()}`}>{score.potential} potential</p></div><button className="secondary-button" disabled={analyzing} onClick={() => void analyze()} type="button">{analyzing ? "Analyzing opportunity…" : "Re-score opportunity"}</button></div><p className="muted-copy">This is an opportunity quality score, not a probability of publication.</p><div className="dimension-list">{Object.entries(score.metadata.dimensions).map(([key, dimension]) => <details className="dimension" key={key}><summary><span>{labels[key]}</span><strong>{dimension.score}</strong></summary><div className="dimension-details">{dimension.positive_factors.map((factor) => <p key={factor.factor}>✓ {factor.factor} <span>+{factor.impact}</span></p>)}{dimension.negative_factors.map((factor) => <p className="negative" key={factor.factor}>⚠ {factor.factor} <span>{factor.impact}</span></p>)}{dimension.missing_information.length > 0 && <p className="missing">Missing information: {dimension.missing_information.join(", ")}</p>}</div></details>)}</div>{history.length > 1 && <p className="score-history">Score history: {history.length} saved analyses. Previous results are preserved.</p>}</>}</section>;
}
