# Generated by Django 6.1 on 2026-08-21 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('angles', '0003_rename_angles_angle_opportu_2a48cf_idx_angles_angl_opportu_b9d28d_idx'),
        ('opportunities', '0001_initial'),
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryStrengtheningAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strengthening_analyses', to='opportunities.opportunity')),
                ('score', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strengthening_analyses', to='scoring.opportunityscore')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StoryStrengtheningRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('weakness', models.TextField()),
                ('affected_dimension', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('explanation', models.TextField()),
                ('recommendation', models.TextField()),
                ('required_information', models.JSONField(default=list)),
                ('required_evidence', models.JSONField(default=list)),
                ('expected_benefit', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=20)),
                ('source_factors', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='strengthening.storystrengtheninganalysis')),
                ('angle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strengthening_recommendations', to='angles.prangle')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strengthening_recommendations', to='opportunities.opportunity')),
            ],
            options={
                'ordering': ['severity', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='storystrengtheninganalysis',
            index=models.Index(fields=['opportunity', '-created_at'], name='strengtheni_opportu_bdef32_idx'),
        ),
        migrations.AddIndex(
            model_name='storystrengtheningrecommendation',
            index=models.Index(fields=['opportunity', 'status'], name='strengtheni_opportu_0c91fc_idx'),
        ),
    ]
