# Generated by Django 6.1 on 2026-08-21 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angles', '0002_anglegeneration_score_optional'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='anglegeneration',
            new_name='angles_angl_opportu_b9d28d_idx',
            old_name='angles_angle_opportu_2a48cf_idx',
        ),
    ]
