# Generated by Django 6.1 on 2026-08-20.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("company_name", models.CharField(max_length=255)),
                ("industry", models.CharField(max_length=150)),
                ("location", models.CharField(max_length=255)),
                ("website", models.URLField(max_length=500)),
                ("description", models.TextField()),
                ("company_size", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("authorized_consultants", models.ManyToManyField(blank=True, related_name="authorized_clients", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_clients", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["company_name", "id"]},
        )
    ]
