# Generated by Django 6.1 on 2026-08-21.
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("opportunities", "0001_initial")]
    operations = [
        migrations.CreateModel(name="OpportunityExtraction", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("provider", models.CharField(max_length=100)), ("model_identifier", models.CharField(max_length=255)), ("status", models.CharField(choices=[("completed", "Completed"), ("failed", "Failed")], default="completed", max_length=20)), ("extracted_data", models.JSONField(default=dict)), ("created_at", models.DateTimeField(auto_now_add=True)), ("opportunity", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="extractions", to="opportunities.opportunity"))], options={"ordering": ["-created_at", "-id"]}),
        migrations.CreateModel(name="ExtractionConfirmation", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("decisions", models.JSONField(default=dict)), ("confirmed_at", models.DateTimeField(auto_now_add=True)), ("confirmed_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="extraction_confirmations", to=settings.AUTH_USER_MODEL)), ("extraction", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="confirmation", to="extraction.opportunityextraction"))]),
    ]
