# Generated by Django 6.1 on 2026-08-21.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("clients", "0001_initial")]
    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)), ("description", models.TextField(blank=True)),
                ("story_type", models.CharField(blank=True, max_length=100)),
                ("funding_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ("funding_stage", models.CharField(blank=True, max_length=100)),
                ("founder_available", models.BooleanField(blank=True, null=True)),
                ("product_launched", models.BooleanField(blank=True, null=True)),
                ("product_launch_date", models.DateField(blank=True, null=True)),
                ("customer_count", models.PositiveIntegerField(blank=True, null=True)),
                ("revenue_information", models.TextField(blank=True)), ("geographic_relevance", models.TextField(blank=True)),
                ("target_audience", models.TextField(blank=True)), ("supporting_information", models.TextField(blank=True)),
                ("client_briefing", models.TextField()),
                ("status", models.CharField(choices=[("draft", "Draft"), ("ready_for_analysis", "Ready for analysis"), ("analyzed", "Analyzed"), ("archived", "Archived")], default="draft", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="opportunities", to="clients.client")),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_opportunities", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-updated_at", "-id"]},
        ),
        migrations.AddIndex(model_name="opportunity", index=models.Index(fields=["client", "status"], name="opportuniti_client__4d9865_idx")),
        migrations.AddIndex(model_name="opportunity", index=models.Index(fields=["status", "-updated_at"], name="opportuniti_status_70dc5d_idx")),
    ]
